a1ien/rusb

src/device_handle.rs
See my comment here: https://github.com/dcuddeback/libusb-rs/issues/21#issuecomment-530202234
=> Use a buffer of size 255 not 256 for lang/description

README.md
Its pretty handy that no setup is required, thanks for your work on this fork!
However if we dont include it in the readme, then no one will know.
=> Improve readme deps instructions

README.md
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
=> README: Fix libusb1-sys crate name

src/device_handle.rs
This is useful for when we get the device handle using vid/pid, e.g., `rusb::open_device_with_vid_pid`, and we need access to something that's only accessible through the `Device` itself, libusb-1.0 offeres this with [libusb_get_device](http://libusb.sourceforge.net/api-1.0/group__libusb__dev.html#gafe70b8a797893d4d16985980acec956a), but rusb still didn't support this functionality.
=> Add method to DeviceHandle to get the corresponding Device

src/device_handle.rs
Similar to #16 this checks for a malformed string descriptor 0 via `read_languages()`
It does the same sanity checks as in `read-string_descriptor()`. It checks that the whole descriptor was read (lengths match), an even number of bytes were read, etc.
Strangely, this issue popped up on Linux, but only when running with root privileges.
=> Check for bad or empty descriptor in read_languages()

src/device_handle.rs, src/error.rs
As 0.6 release seems like obvious, I took a look at the code and did minor rework so those changes could go in, if approved, on the same release.
Take a look at the proposed changes.
=> Some rework aiming for 0.6 inclusion

src/device.rs
Add the `get_parent` API from libusb-sys `libusb_get_parent`
=> Add get_parent

src/device.rs
Add `port_numbers` API.
The result of #41 maybe taken into account before.
=> Add port_numbers API

Cargo.toml, build.rs, examples/hotplug.rs, src/context.rs
Breaking change in hotplug api.
Now Registration implement Drop for cleanup resource and automatic deregister callback
Fix #6
=> Fix leak in hotplug

src/context.rs
@kevinmehall  what do you think about this fix?
Close #54
=> Fix UB in hotplug_callback.

.gitmodules, Cargo.toml, README.md, libusb1-sys/Cargo.toml, libusb1-sys/LICENSE, libusb1-sys/README.md, libusb1-sys/build.rs, libusb1-sys/examples/libusb_info.rs, libusb1-sys/examples/list_devices.rs, libusb1-sys/examples/read_device.rs, libusb1-sys/src/constants.rs, libusb1-sys/src/lib.rs, libusb1-sys/tests/test.rs
I decide to merge two repositories in one. [libusb1-sys](https://github.com/a1ien/libusb1-sys) is hosted now in the current repository. It will allow to easy maintenance a project.
=> libusb1-sys merge

src/fields.rs
As titled.
Thanks for all your work with the crate, this is excellent!
=> Implement Display for Version.

src/endpoint_descriptor.rs
=> Add getters for bRefresh and bSynchAddress

CHANGELOG.md, src/lib.rs
=> Re-export libusb1_sys as ffi

src/context.rs
There is no reason not to, I suppose.
=> Derive Debug for Context

src/device_handle.rs
Remove unnecessary vector allocation.
=> Improve read_string_descriptor

examples/list_devices.rs, src/config_descriptor.rs, src/interface_descriptor.rs
=> ConfigDescriptor and InterfaceDescriptor extra return just slice

examples/hotplug.rs, src/context.rs, src/hotplug.rs, src/lib.rs
Add new struct HotplugBuilder
Deprecate register_callback
Fix documentation warning
Close #100
=> Rewrite hotplug registration

CHANGELOG.md, Cargo.toml, README.md, libusb1-sys/CHANGELOG.md, libusb1-sys/Cargo.toml, libusb1-sys/README.md
rusb 0.9.0
libusb1-sys 0.6.0
This only PR. I will publish to crate.io when merge this PR. I plan to do it next week
=> Prepare release

Cargo.toml, examples/list_devices.rs
Like lsusb.
Example:
```
Bus 005 Device 004 ID 046d:082d  480 Mbps                                                                                               
Device Descriptor:                      
bcdUSB              2.00                  
bDeviceClass        0xef                                  
bDeviceSubClass     0x02                                          
bDeviceProtocol     0x01                                       
bMaxPacketSize0       64                                     
idVendor          0x046d Logitech, Inc.                
idProduct         0x082d HD Pro Webcam C920
```
=> examples: list_devices: Add vendor and product name

libusb1-sys/build.rs
Hi 👋 
This patch allowed me to compile libusb1-sys on macOS statically.  Without the logic for skipping `-lobjc` (which comes from `pkg-config --static` output — erroneously I believe), I get a cargo compilation error:
```
% env LIBUSB_STATIC=1 cargo build
Compiling libusb1-sys v0.6.2 (/Users/adaszko/repos/rusb/libusb1-sys)
Compiling rusb v0.9.1
error: could not find native static library `objc`, perhaps an -L flag is missing?
```
I see [a similar workaround is implemented for the vendoring case](https://github.com/a1ien/rusb/blob/a7eb4b79b7b5d59c1161f07746d27ff05ed9a186/libusb1-sys/build.rs#L111) already.
=> Patch for macOS Big Sur and newer allowing to link statically

libusb1-sys/build.rs
=> Bump libusb to 1.0.27
