a1ien/rusb

src/context.rs
src/lib.rs
src/options.rs

The log level could already be set, this is purely to enable setting `LIBUSB_OPTION_USE_USBDK` for use with [UsbDk](https://github.com/daynix/UsbDk) on Windows. This option has to be set right after `libusb_init`, so there's no public way of applying a `UsbOption` to an already opened context.

Allow setting libusb options

---

Cargo.toml
src/device_handle.rs

When this is enabled libusb will automatically detach the kernel
driver on an interface when claiming the interface, and attach it when
releasing the interface.
Automatic kernel driver detachment is disabled on newly opened device
handles by default.
On platforms which do not have support, this function will return
`Error::NotSupported`, and rusb will continue as if this function was
never called.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

device_handle: Enable automatic kernel driver detachment

---

Cargo.toml

This is related to: https://github.com/a1ien/libusb1-sys/pull/13

Add vendored feature to force libusb-1.0 build

---

src/device_handle.rs
src/error.rs

Adds some sanity checks on the string descriptor returned by a device before trying to parse the string. For example, the byte length should be even since the unicode string has 2-bytes per char.
This also checks for an empty string, in which `len == 2` is just for the header, with zero bytes for the string. This succeeds and returns an empty string.

[#15] Check for bad or empty strings in read_string_descriptor()

---

src/device_handle.rs

Minor update. This just removes some unsafe code from `read_string_descriptor_ascii()`, like what was done in #16 and #17.

Removed unsafe buf_slice from read_string_descriptor_ascii()

---

src/error.rs

This workaroud an issue we found when supporting a customer which the
lib triggered a segfault when displaying a error on 32bits platforms.
We reported the issue to Rust compiler, but the workaroud is indeed good
as even when this gets fixed on newer releases of the compiler, old
versions will still be affected and this is a very difficult kind of bug
to find.
Refs: https://github.com/rust-lang/rust/issues/73151
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

error: Avoid consuming the `Error` when returning the error string

---

Cargo.toml
src/device_handle.rs

Create a new struct, ClaimedInterfaces, which is responsible for
tracking the claimed interfaces of a particular DeviceHandle.
Add tests for ClaimedInterfaces.
Replace usages of BitSet with this ClaimedInterfaces struct within
DeviceHandle.
Remove dependency on bit-set from the crate.
Fixes #29

device_handle: replace BitSet with new struct

---

Cargo.toml
src/context.rs
src/device.rs
src/device_handle.rs
src/device_list.rs
src/lib.rs

Sorry for the 2nd PR, but I had to fight some libusb bugs to confirm this works, and it does!
With this PR, folks can use rust on Android as non-root users.

Expose from_libusb() methods to import devices from Android

---

src/context.rs

As mention #44 UsbContext trait has neither Send nor Sync bound and can be implemented from the user side. This permits writing a custom non-thread safe UsbContext implementation in safe Rust code, which can cause a data race when used with Device or DeviceHandle.
So required UsbContext implement Send + Sync
Fix #44

Fix Unsound Send/Sync bound for Device and DeviceHandle

---

src/device.rs
src/device_handle.rs

I'm experimenting with abstractions for the libusb async APIs that don't necessarily belong in the `rusb` crate itself. It would be nice if these APIs could accept a `DeviceHandle` and not also need to have the `Context` passed separately for the `libusb_handle_events*` functions.

Add Device/DeviceHandle::context getter methods

---

libusb1-sys/src/lib.rs

Allow null function pointers for libusb_set_pollfd_notifiers().

---

libusb1-sys/CHANGELOG.md
libusb1-sys/Cargo.toml
libusb1-sys/src/lib.rs

[libusb_set_log_cb](https://libusb.sourceforge.io/api-1.0/group__libusb__lib.html#ga2efb66b8f16ffb0851f3907794c06e20) cb: pointer to the callback function, or NULL to stop log messages redirection

Allow null function pointers for libusb_set_log_cb

---

src/device_handle.rs

This PR adds a `fmt::Debug` impl for `DeviceHandle`. To make it a bit more useful for users, it includes the `Debug` output from the `Device` referenced by the handle.

impl Debug for DeviceHandle

---

src/language.rs

Fixes:
warning: this URL is not a hyperlink

Fix cargo doc warning

---

examples/hotplug.rs
src/context.rs

This exposes the hotplug enumerate flag as a `bool` argument to `register_callback()`.  Since this is technically an API-breaking change, I thought I might as well break it more and rename the functions to match the ones in `libusb` (I, personally, had trouble finding them in the docs because they did not have "hotplug" in the name). If you're not a fan of that, that's fine, I'll put it back. I also added some documentation.
One more thing — a thing that tripped me up was not realising that the callback is unregistered when the returned `Registration` is dropped. I added this to the docs, but do you think it would be worth adding a `must_use` attribute to the return value of the register function?

Expose the hotplug enumerate flag

---

src/device_handle.rs

As exotic as it may be, libusbredir requires to give the device handle
ownership to the library. This function helps to achieve this, without
having to leak the a DeviceHandle with mem::forget.

Add DeviceHandle::into_raw()

---

libusb1-sys/src/lib.rs
src/context.rs

Depends on https://github.com/a1ien/rusb/pull/97

Add Context::interrupt_handle_events()

---

libusb1-sys/build.rs

As libusb is include in the FreeBSD base system[1], we should just use the
os provided version.
This'll also fix a compilation error, the pressences of the libudev devd
compatibility interface[2] cause linux header to be included.
[1]: https://cgit.freebsd.org/src/tree/lib/libusb
[2]: https://www.freshports.org/devel/libudev-devd

Ignore vendored feature on FreeBSD

---

libusb1-sys/build.rs

Previously, building a recent version of libusb on macOS as a vendored copy would fail with a linker error. Specifically, commit
[6a902c3b207a017cd699ac8bb6659abf32eb0c99 of libusb](https://github.com/libusb/libusb/commit/6a902c3b207a017cd699ac8bb6659abf32eb0c99)
requires that the environment variable `TARGET_OS_OSX` is set on macOS targets and needs to link against Security.framework. I have verified that these changes allow the build to complete successfully on both macOS 10.13 High Sierra and macOS 11 Big Sur.
If one uses the version of libusb that you include as a submodule, you do not yet run into this issue, however it occurs if that version is swapped out with a never version. As soon as libusb releases a new version and you update, this change will also be necessary. However, I …

Fix building of recent libusb on macOS

---

src/context.rs

See API documentation for details.

context: add open_device_with_fd()

---

src/fields.rs

This is useful for the [hackrfone](https://crates.io/crates/hackrfone) crate where we need to compare the device version to determine if a feature is supported.

impl Ord and PartialOrd for Version

---

examples/read_device.rs

- Use base 16 as arguments
- Panic if something goes wrong when opening the device

examples: read_devices: Improve usage

---

libusb1-sys/build.rs

This should fix #117.
The name doesn't really matter, since static linking is used. By changing the name from `libusb.a`, a conflict with the system package is avoided.

Rename compiled library when vendored libusb is used

---

src/context.rs

Allows to create context separately, initialize libusb, and then initialize `Context` with it.
The ability to create Context from existing context is necessary to use rusb with Android because on Android `libusb_init` should be called with special option that prevents device enumeration. More on it [here](https://github.com/libusb/libusb/blob/master/android/README).

context: create rusb `Context` from existing `libusb_context`

---

src/config_descriptor.rs

The config in these tests was freed when the call to from_libusb returns,
thus all access through the pointer afterwards would be invalid.

Fix stack use after scope in tests

---

src/language.rs

Fixes misspelling of United Kingdom in languages documentation.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
> Thanks for your great work on this crate!

Fix United Kingdom misspelling in languages docs

---

libusb1-sys/build.rs

Headers (libudev.h in this case) may not always reside in the default system-wide include directories.

Add libudev include paths as specified by pkg-config

---

src/fields.rs

Make request_type function in fields.rs a const fn so that it can used
to create const global variables.
Test: The following code now compiles
```
const CTRL_OUT: u8 = request_type(
rusb::Direction::Out,
rusb::RequestType::Vendor,
rusb::Recipient::Device,
);
```

fields.rs: Make request_type function a const fn

---

src/config_descriptor.rs
src/interface_descriptor.rs

From my understanding, all state derived from a `ConfigDescriptor` has a lifetime associated to that `ConfigDescriptor`. So, it's safe for the `EndpointDescriptor` to adopt the `ConfigDescriptor`'s lifetime through the `InterfaceDescriptor`.
The new test shows us that the lifetimes are now all equal. This test wouldn't compile without the signature change.

Increase endpoint descriptor's lifetime

---

src/device_handle.rs

Documentation specifies micros, but libusb consumes millis. Therefore passing in 1 micro results in an infinite timeout, not the shortest timeout.

Fix timeout documentation

---

src/lib.rs
src/options.rs

Hello !
This commit adds a convenient function to disable scanning devices in **libusb_init()**, see https://libusb.sourceforge.io/api-1.0/group__libusb__lib.html#gga07d4ec54cf575d672ba94c72b3c0de7ca5534030a8299c85555aebfae39161ef7

Add a function to disable device discovery

---

src/language.rs

The previous link is no longer available and I've update it with the one that I found on the official USB website:
(scroll at to the end) https://www.usb.org/deprecated-links-and-tools

fix: 404 link for languages

---

Cargo.toml
src/error.rs
src/fields.rs

Ref #81
I have only implemented serialization/deserialization for the public enums for now. The structs largely depended on the types in libusb1-sys, which is nontrivial to serialize due to things like raw pointers and user defined data, and doesn't really make sense to deserialize (AFAIK).
The serialization is hidden behind the `serde` feature flag.

Add serde support for public enums

---

CHANGELOG.md
Cargo.toml

Added items to changelog and bumped `Cargo.toml` version

Prepare release for rusb 0.9.3

---

examples/list_devices.rs
src/config_descriptor.rs
src/device_descriptor.rs
src/endpoint_descriptor.rs
src/interface_descriptor.rs

Adds getters for bLength, bDescriptorType and wTotalLength to descriptors. Includes them in list devices lsusb verbose example to make it more feature complete.
Is there a reason these are not present and I'm missing it? Rather than ask in an issue I thought it's more productive to add them and ask here.

bLength, bDescriptorType and wTotalLength to descriptors

---

src/device_handle.rs

Change the following methods to accept a non-exclusive reference:
- DeviceHandle::set_active_configuration
- DeviceHandle::unconfigure
- DeviceHandle::reset
- DeviceHandle::clear_halt
- DeviceHandle::detach_kernel_driver
- DeviceHandle::attach_kernel_driver
- DeviceHandle::set_auto_detach_kernel_driver
- DeviceHandle::claim_interface
- DeviceHandle::release_interface
- DeviceHandle::set_alternate_setting
This is safe to do because libusb is thread-safe.
Fixes #148

Use &self reference for all DeviceHandle methods

---

libusb1-sys/build.rs

Supporting pkg-config provides convenience for using precompiled library files.

Support pkg_config for MSVC.

---

src/context.rs
src/lib.rs

Good day.
This pr suggests some API updates to support log callbacks.
Log callback setup:
```
let mut context = rusb::Context::new()?;
context.set_log_level(rusb::LogLevel::Info);
let cb = Box::new(move |level: rusb::LogLevel, text: String| {
println!(log_file, "[{:#?}] {}", level, text).ok();
});
context.set_log_callback(cb, rusb::LogCallbackMode::Context);
```
You can take this changes as a base for your own API or just merge it as is.

Log callback API added

---

libusb1-sys/Cargo.toml
libusb1-sys/build.rs

Hi!
I and @dragonmux found two issues when building libusb from a MSVC host to a MinGW target. When the build.rs script is built for the MSVC host,
- the vcpkg crate is used for detection (which correctly detects the MinGW target and reports an unsupported ABI)
- a MSVC flag is applied to the build (and thus breaking the build altogether)
This commit fixes both issues by changing vcpkg to a Windows-wide dependency, and then if CARGO_CFG_TARGET_ENV is indeed MSVC, it is used and the /source-charset:utf-8 flag is applied.
Please let us know what you think.

Fix package detection and build when cross-compiling from MSVC to GNU

---

libusb1-sys/src/lib.rs

This prevents panics on debug builds in new rust nightly versions (as of 2024-03-27), since they added bounds checks to `get_unchecked_mut`, which here was called on a zero-length slice representing a flexible array member. See: https://github.com/rust-lang/rust/commit/2b43e75c98cc5ae32328c8b49657bcd882eb5e75
TBH I am still learning rust, so if there is any better way of doing this let me know and I will change it.

Replace .get_unchecked_mut() with .as_mut_ptr().add() when accessing iso_packet_desc (fixes #199)

---

libusb1-sys/src/lib.rs

Merge request #197 as one commit as requested.
Since libusb_get_pollfds() is already available in the FFI, this PR adds the libusb_free_pollfds() method from libusb available in the FFI.
Libusb documentation of libusb_free_pollfds() states : "This should be called for all pollfd lists allocated with libusb_get_pollfds()"

Add libusb_free_pollfds() in the available FFI methods.

---

libusb1-sys/src/lib.rs

This fix adds missing fields to these two structs so that they can be used from rust without the size mismatching from the C version.
See:
https://libusb.sourceforge.io/api-1.0/structlibusb__bos__descriptor.html 
https://libusb.sourceforge.io/api-1.0/structlibusb__bos__dev__capability__descriptor.html

fix: Add missing fields to libusb_bos_descriptor and libusb_bos_dev_capability_descriptor

---

CHANGELOG.md
Cargo.toml
libusb1-sys/CHANGELOG.md
libusb1-sys/Cargo.toml

libusb 0.7.0
* fix: Add missing fields to libusb_bos_descriptor and libusb_bos_dev_capability_descriptor
* Bump libusb to 1.0.27
* Remove unneeded mut
rusb 0.9.4
* bLength, bDescriptorType and wTotalLength to descriptors
* Use &self reference for all DeviceHandle methods
* fix: panic when trying to iterate over an interface with zero endpoints
* Log callback API added
* Bump libusb1-sys 0.7.0

Bump rusb 0.9.4 and libusb1-sys 0.7

---

libusb1-sys/src/lib.rs

The original `libusb_init(...)` has been deprecated by libusb. On Android, when using `libusb_init()` without configuring libusb to skip scanning at context-init time, libusb is prone to crashing.
Added this function to libusb1-sys

Add libusb_init_context and associated structs

---

libusb1-sys/build.rs

Android does not have udev; cross-compiling on a Linux host with udev results in a link to the same.
This patch refuses to enable udev if building for an android target.

Android does not have udev; Do not link to udev on Android

---

src/language.rs

Hi, I have added the ability to specify a desired language rather than explicitly reading it. This has come up in some of the devices I have been working with, where it needs to be over ridden or used for testing/debugging. I believe it also helps with #93 and #214. 
I have:
- run `cargo fmt`
- run `cargo test`
- added appropriate documentation.

Added new constructor for languages + tests
